[build]
builder = "nixpacks"

[deploy]
startCommand = "FLASK_APP='app:create_app()' flask db upgrade && gunicorn --timeout 120 'app:create_app()'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 60
