"""add partner pricing model fields

Revision ID: bcbd0320fcb0
Revises: m3n4o5p6q7r8
Create Date: 2026-03-07 10:48:51.242073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbd0320fcb0'
down_revision = 'm3n4o5p6q7r8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cost_per_voicemail', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weekly_minimum_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weekly_minimum_calls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualified_call_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cost_per_qualified_call', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('cost_per_lead',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))

    with op.batch_alter_table('shared_dashboards', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_recordings',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_transcripts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('tracking_lines', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_lines', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('shared_dashboards', schema=None) as batch_op:
        batch_op.alter_column('show_transcripts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_recordings',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('cost_per_lead',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.drop_column('cost_per_qualified_call')
        batch_op.drop_column('qualified_call_seconds')
        batch_op.drop_column('weekly_minimum_calls')
        batch_op.drop_column('weekly_minimum_fee')
        batch_op.drop_column('cost_per_voicemail')
        batch_op.drop_column('pricing_model')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
